name: granter_app
description: A new Flutter project.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  provider: ^6.0.2 # provider state management
  auto_size_text_pk: ^3.0.0 # text responsible
  intl: ^0.17.0 # date formatter
  firebase_core: ^1.6.0 # firebase core
  cloud_firestore: ^3.1.5 # firebase firestore
  firebase_storage: ^10.0.3 # firebase storage
  file_picker: ^4.0.3 # upload local images
  cached_network_image: ^3.2.0 # cache network images

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
